config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
      resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end
  def show
    @review = Review.new
  end
  def new
    @restaurant = Restaurant.new
  end
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end
  def edit
  end
  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end
  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end
  def restaurant_params # strong params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
      @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    # we need @restaurant in our `simple_form_for`
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>RailsYelpMvp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address%>
  <%= f.text_field :address %>
    <%= f.label :category%>
  <%= f.text_field :category %>
    <%= f.label :phone_number%>
  <%= f.text_field :phone_number %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= render'form' %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
  <li>

    <%=  restaurant.name %>
    <%=  restaurant.address %>
    <%=  restaurant.phone_number %>
    <%=  restaurant.category %>
    <%= link_to "show restaurant", restaurant_path(restaurant) %>
    <%= link_to "edit restaurant", edit_restaurant_path(restaurant) %>
    <%= link_to "delete article", restaurant_path(restaurant), method: :delete %>
  </li>
  <% end %>
</ul>

<%= link_to "Add new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= render'form' %>

app/views/restaurants/show.html.erb
<h1> <%= @restaurant.name %></h1>

<h2>Reviews</h2>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li>
      <%= review.content %>
      <%= review.rating %>
    </li>
  <% end %>
</ul>

<h1>New Review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

<%= link_to "Write Review", new_restaurant_review_path(@restaurant) %>
<%= link_to "Back to restaurants", restaurants_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>